### ISSUE TITLE
Q: Should the high level wrappers for iterating over descriptor memory be in their own crate or a common library?

### ISSUE THREAD

**Issue by stsquad** [slp/virtiofsd-rs#1]
https://github.com/slp/virtiofsd-rs/blob/62cc4019073b9cd592156d2305bd346f2176172b/src/descriptor_utils.rs#L178

I'm just wonder what the difference is between these wrappers and what is provided by the rust-vmm/vm-memory crate?

**Comment by slp** [comment]
The `Reader` and `Writer` over the `DescriptorChainConsumer` are very convenient because they allow you to operate with a descriptor chain as if was a regular buffer. That said, it would probably be a good to try to move that to `vm-memory`, as an optional feature.

BTW, would you mind asking this again in the [official repository](https://gitlab.com/virtio-fs/virtiofsd-rs)? I would like to delete this repo ASAP to avoid confusions, and it would nice to preserve this info.

**Comment by stsquad** [comment]
Sure will do. I'll update my links while I'm at it ;-)
